from django.urls import path
from social_center_app.views import *

urlpatterns = [
    path('user/', UserView.as_view()),
    path('clients/', ClientView.as_view()),
    path('client/', ClientInformationView.as_view()),
    path('client/<int:pk>', ClientInformationView.as_view()),
    path('socialBehavior/', ASocialBehaviorView.as_view()),
    path('socialBehavior/<int:pk>', ASocialBehaviorView.as_view()),
    path('chronicDisease/', ChronicDiseaseView.as_view()),
    path('chronicDisease/<int:pk>', ChronicDiseaseView.as_view()),
    path('children/', ChildListView.as_view()),
    path('child/', ChildView.as_view()),
    path('child/<int:pk>', ChildView.as_view()),
    path('familyMembers/', FamilyMembersInformationView.as_view()),
    path('familyMembers/<int:pk>', FamilyMembersInformationView.as_view()),
    path('husbands/', HusbandListView.as_view()),
    path('husbandInformation/', HusbandInformationView.as_view()),
    path('husbandInformation/<int:pk>', HusbandInformationView.as_view()),
    path('socialLiving/', SocialLivingConditionView.as_view()),
    path('socialLiving/<int:pk>', SocialLivingConditionView.as_view()),
    path('socialEconomic/', SocialEconomicConditionView.as_view()),
    path('socialEconomic/<int:pk>', SocialEconomicConditionView.as_view()),
    path('sourceIncome/', SourceIncomeView.as_view()),
    path('sourceIncome/<int:pk>', SourceIncomeView.as_view()),
    path('socialPayment/', SocialPaymentView.as_view()),
    path('socialPayment/<int:pk>', SocialPaymentView.as_view()),
    path('childAllowance/', ChildAllowanceAndCompensationView.as_view()),
    path('childAllowance/<int:pk>', ChildAllowanceAndCompensationView.as_view()),
    path('facilities/', FacilitiesView.as_view()),
    path('facilities/<int:pk>', FacilitiesView.as_view()),
    path('expertOpinion/', ExpertOpinionView.as_view()),
    path('expertOpinion/<int:pk>', ExpertOpinionView.as_view()),
    path('testBoykoList/', TestBoykoListView.as_view()),
    path('testBoyko/', TestBoykoView.as_view()),
    path('testBoyko/<int:pk>', TestBoykoView.as_view()),
    path('interpretationBoyko/', InterpretationBoykoView.as_view()),
    path('testGAGEList/', TestGAGEListView.as_view()),
    path('testGAGE/', TestGAGEView.as_view()),
    path('testGAGE/<int:pk>', TestGAGEView.as_view()),
    path('interpretationGAGE/', InterpretationGAGEView.as_view()),
    path('testSOCRATESList/', TestSOCRATESListView.as_view()),
    path('testSOCRATES/', TestSOCRATESView.as_view()),
    path('testSOCRATES/<int:pk>', TestSOCRATESView.as_view()),
    path('interpretationSOCRATES/', InterpretationSOCRATESView.as_view()),
    path('typologicalGroupList/', TypologicalGroupListView.as_view()),
    path('typologicalGroup/', TypologicalGroupView.as_view()),
    path('typologicalGroup/<int:pk>', TypologicalGroupView.as_view()),
    path('fieldsGroup/', FieldsGroupView.as_view()),
    path('fields/', FieldsView.as_view()),
    path('graphicBoyko/', GraphicBoykoView.as_view()),
    path('graphicGAGE/', GraphicGAGEView.as_view()),
    path('graphicSOCRATES/', GraphicSOCRATESView.as_view()),
    path('get-table/', GetTable.as_view()),
    path('userCrud/', UserCRUDView.as_view()),
    path('tests/', TestsAnswers.as_view())
]
