# Generated by Django 3.1.2 on 2020-10-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='municipalDistrict',
            field=models.IntegerField(blank=True, choices=[(1, 'Юго-Запад'), (2, 'Южно-Приморский'), (3, 'Сосновая Поляна'), (4, 'Урицк'), (5, 'Константиновское'), (6, 'Горелово'), (7, 'г.Красное Село')], null=True, verbose_name='Муниципальный округ'),
        ),
    ]
