# Generated by Django 3.0.8 on 2020-07-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='asocialbehavior',
            options={'verbose_name': 'Информация о противоправных действиях, правонарушениях, употреблении наркотиков, алкоголя', 'verbose_name_plural': 'Информация о противоправных действиях, правонарушениях, употреблении наркотиков, алкоголя'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Ребенок', 'verbose_name_plural': 'Дети'},
        ),
        migrations.AlterModelOptions(
            name='childallowanceandcompensation',
            options={'verbose_name': 'Детские пособия и компенсационные выплаты', 'verbose_name_plural': 'Детские пособия и компенсационные выплаты'},
        ),
        migrations.AlterModelOptions(
            name='chronicdisease',
            options={'verbose_name': 'Информация о наличии хронического заболевания', 'verbose_name_plural': 'Информация о наличии хронического заболевания'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='expertopinion',
            options={'verbose_name': 'Заключение специалиста', 'verbose_name_plural': 'Заключения специалиста'},
        ),
        migrations.AlterModelOptions(
            name='facilities',
            options={'verbose_name': 'Льготы и меры социальной поддержки,предусмотренные для определенных категорий', 'verbose_name_plural': 'Льготы и меры социальной поддержки,предусмотренные для определенных категорий'},
        ),
        migrations.AlterModelOptions(
            name='familymembersinformation',
            options={'verbose_name': 'Сведения о членах семьи', 'verbose_name_plural': 'Сведения о членах семьи'},
        ),
        migrations.AlterModelOptions(
            name='generalinformation',
            options={'verbose_name': 'Общая информация', 'verbose_name_plural': 'Общая информация'},
        ),
        migrations.AlterModelOptions(
            name='healthchild',
            options={'verbose_name': 'Информация о состоянии здоровья ребенка', 'verbose_name_plural': 'Информация о состоянии здоровья ребенка'},
        ),
        migrations.AlterModelOptions(
            name='husbandinformation',
            options={'verbose_name': 'Информация о муже/партнёре', 'verbose_name_plural': 'Информация о муже/партнёре'},
        ),
        migrations.AlterModelOptions(
            name='interpretation',
            options={'verbose_name': 'Интерпретация', 'verbose_name_plural': 'Интерпретации'},
        ),
        migrations.AlterModelOptions(
            name='passingthetest',
            options={'verbose_name': 'Прохождение теста', 'verbose_name_plural': 'Прохождения тестов'},
        ),
        migrations.AlterModelOptions(
            name='possibleanswer',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='socialeconomiccondition',
            options={'verbose_name': 'Социально экономические условия проживания', 'verbose_name_plural': 'Социально экономические условия проживания'},
        ),
        migrations.AlterModelOptions(
            name='sociallivingcondition',
            options={'verbose_name': 'Социально бытовые условия', 'verbose_name_plural': 'Социально бытовые условия'},
        ),
        migrations.AlterModelOptions(
            name='socialpayment',
            options={'verbose_name': 'Социальные выплаты', 'verbose_name_plural': 'Социальные выплаты'},
        ),
        migrations.AlterModelOptions(
            name='sourceincome',
            options={'verbose_name': 'Источники дохода', 'verbose_name_plural': 'Источники дохода'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
    ]
