# Generated by Django 3.0.8 on 2020-07-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0002_auto_20200715_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asocialbehavior',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_center_app.Client'),
        ),
        migrations.AlterField(
            model_name='chronicdisease',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_center_app.Client'),
        ),
        migrations.AlterField(
            model_name='expertopinion',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_center_app.Client'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_center_app.Client'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='husband',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_center_app.FamilyMembersInformation'),
        ),
    ]
