# Generated by Django 3.1.2 on 2020-11-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0002_auto_20201108_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typologicalgroup',
            name='subgroup',
        ),
        migrations.AlterField(
            model_name='typologicalgroup',
            name='group',
            field=models.IntegerField(choices=[(0, 'Клиент не может быть относен к типологической группе потребителей ПАВ'), (1, 'Группа 1 «Женщины, активно употребляющие ПАВ, противопоставляющие себя социуму»'), (2, 'Группа 2.1 «Молодые женщины с социально-бытовыми проблемами в период неактивного употребления ПАВ»'), (3, 'Группа 2.2 «Женщины с длительным стажем употребления ПАВ и сопутствующими социально-медицинскими проблемами»')], verbose_name='Основная типологическая группа'),
        ),
    ]
