# Generated by Django 3.1.2 on 2020-10-24 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0002_auto_20201017_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chronicdisease',
            name='frequencyOfVisitsAIDSCenter',
        ),
        migrations.RemoveField(
            model_name='client',
            name='dateOfCertified',
        ),
        migrations.RemoveField(
            model_name='familymembersinformation',
            name='regularPartner',
        ),
        migrations.RemoveField(
            model_name='husbandinformation',
            name='husband',
        ),
        migrations.AddField(
            model_name='asocialbehavior',
            name='DateOfTerminationIPR',
            field=models.DateField(blank=True, null=True, verbose_name='Дата прекращения ИПР'),
        ),
        migrations.AddField(
            model_name='asocialbehavior',
            name='dateOfResolutionIPR',
            field=models.DateField(blank=True, null=True, verbose_name='Дата постановления ИПР'),
        ),
        migrations.AddField(
            model_name='asocialbehavior',
            name='resolutionNumber',
            field=models.TextField(blank=True, null=True, verbose_name='Номер постановления'),
        ),
        migrations.AddField(
            model_name='asocialbehavior',
            name='terminationNumber',
            field=models.TextField(blank=True, null=True, verbose_name='Номер прекращения'),
        ),
        migrations.AddField(
            model_name='child',
            name='ContractPeriod',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия договора'),
        ),
        migrations.AddField(
            model_name='child',
            name='DateOfCreationIPSO',
            field=models.DateField(blank=True, null=True, verbose_name='Дата разработки ИППСУ'),
        ),
        migrations.AddField(
            model_name='child',
            name='IPPSNumber',
            field=models.TextField(blank=True, null=True, verbose_name='Номер ИППСУ'),
        ),
        migrations.AddField(
            model_name='child',
            name='contractNumber',
            field=models.TextField(blank=True, null=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='child',
            name='dependence',
            field=models.IntegerField(blank=True, choices=[(1, 'алкогольная'), (2, 'наркотическая'), (3, 'опыт употребления'), (4, 'созависимость')], null=True, verbose_name='Зависимость'),
        ),
        migrations.AddField(
            model_name='child',
            name='placementSocialSupport',
            field=models.IntegerField(blank=True, choices=[(1, 'консилиум'), (2, 'приказ')], null=True, verbose_name='Постановка на социальное сопровождение'),
        ),
        migrations.AddField(
            model_name='client',
            name='ContractPeriod',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия договора'),
        ),
        migrations.AddField(
            model_name='client',
            name='DateOfCreationIPSO',
            field=models.DateField(blank=True, null=True, verbose_name='Дата разработки ИППСУ'),
        ),
        migrations.AddField(
            model_name='client',
            name='IPPSNumber',
            field=models.TextField(blank=True, null=True, verbose_name='Номер ИППСУ'),
        ),
        migrations.AddField(
            model_name='client',
            name='placementSocialSupport',
            field=models.IntegerField(blank=True, choices=[(1, 'консилиум'), (2, 'приказ')], null=True, verbose_name='Постановка на социальное сопровождение'),
        ),
        migrations.AddField(
            model_name='husbandinformation',
            name='ContractPeriod',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия договора'),
        ),
        migrations.AddField(
            model_name='husbandinformation',
            name='DateOfCreationIPSO',
            field=models.DateField(blank=True, null=True, verbose_name='Дата разработки ИППСУ'),
        ),
        migrations.AddField(
            model_name='husbandinformation',
            name='IPPSNumber',
            field=models.TextField(blank=True, null=True, verbose_name='Номер ИППСУ'),
        ),
        migrations.AddField(
            model_name='husbandinformation',
            name='client',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='social_center_app.client'),
        ),
        migrations.AddField(
            model_name='husbandinformation',
            name='contractNumber',
            field=models.TextField(blank=True, null=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='husbandinformation',
            name='placementSocialSupport',
            field=models.IntegerField(blank=True, choices=[(1, 'консилиум'), (2, 'приказ')], null=True, verbose_name='Постановка на социальное сопровождение'),
        ),
        migrations.AlterField(
            model_name='child',
            name='with_mother',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет'), (3, 'не знаю')], null=True, verbose_name='Ребенок выписан из родильного отделения вместе с матерью'),
        ),
        migrations.AlterField(
            model_name='child',
            name='withdrawal_symptoms',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет'), (3, 'не знаю')], null=True, verbose_name='В абстинентном синдроме'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dependence',
            field=models.IntegerField(blank=True, choices=[(1, 'алкогольная'), (2, 'наркотическая'), (3, 'опыт употребления'), (4, 'созависимость')], null=True, verbose_name='Зависимость'),
        ),
        migrations.AlterField(
            model_name='familymembersinformation',
            name='maritalStatus',
            field=models.IntegerField(blank=True, choices=[(1, 'не замужем/не женат'), (2, 'сожительство'), (3, 'замужем/женат'), (4, 'в разводе'), (5, 'вдова/вдовец')], null=True, verbose_name='Семейное положение'),
        ),
        migrations.AlterField(
            model_name='familymembersinformation',
            name='withWhomLiving',
            field=models.IntegerField(blank=True, choices=[(1, 'одна/один'), (2, 'со своими родителями'), (3, 'с родителями партнёра (мужа/жены)'), (4, 'с семьёй (партнёр и дети)'), (5, 'с родственниками')], null=True, verbose_name='С кем проживает'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='fullName',
            field=models.TextField(blank=True, null=True, verbose_name='ФИО партнёра (мужа/жены)'),
        ),
        migrations.AlterField(
            model_name='sociallivingcondition',
            name='ownership',
            field=models.IntegerField(blank=True, choices=[(1, 'договор по найму жилья'), (2, 'собственность клиента'), (3, 'собственность родственников')], null=True, verbose_name='Право собственности,владения и пользования'),
        ),
        migrations.AlterField(
            model_name='testboyko',
            name='child_parent',
            field=models.IntegerField(choices=[(0, 'поддерживает престарелых родителей/несовершеннолетних детей финансово и психологически'), (1, 'есть кратковременные трудности в отношениях с родителями/детьми, о которых известно только очень близким людям'), (2, 'отношение к родителям/детям противоречивое: то заботится, то как будто «забывает» о своей ответственности'), (3, 'формальное отношение к родителям/детям, нет эмоциональной привязанности к ним, тратит деньги только на свои нужды'), (4, 'нет семьи; не заботится о членах семьи, детях даже на минимальном уровне')], verbose_name='9. Забота о детях/родителях'),
        ),
        migrations.AlterField(
            model_name='testboyko',
            name='family_relation',
            field=models.IntegerField(choices=[(0, 'есть семья, желание её иметь и сохранять'), (1, 'есть семья и желание её сохранить, хотя имеются кратковременные трудности в отношениях'), (2, 'конфликты с родственниками, членами семьи, не приводящие к потере контакта с семьей'), (3, 'частые конфликты с членами семьи и близкими, приводящие к долгой разлуке, потере семьи'), (4, 'нет семьи; отсутствует желание иметь и сохранять семью')], verbose_name='8. Семейные отношения'),
        ),
        migrations.AlterField(
            model_name='testgage',
            name='company',
            field=models.IntegerField(blank=True, choices=[(1, 'В компании'), (2, 'В одиночку'), (2, 'В компании и в одиночку')], null=True, verbose_name='3.12. употребляли ли Вы вещества, меняющие настроение, один или в компании?'),
        ),
        migrations.AlterField(
            model_name='testgage',
            name='fault',
            field=models.IntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True, verbose_name='4.3. Вы испытывали когда-нибудь чувство вины по поводу употребления алкоголя (наркотиков)?'),
        ),
        migrations.AlterField(
            model_name='testgage',
            name='how_use',
            field=models.IntegerField(blank=True, choices=[(1, 'Курил, нюхал, глотал'), (2, 'Внутримышечные инъекции'), (3, 'Внутривенные инъекции'), (3, 'Всё выше перечисленное')], null=True, verbose_name='3.9. Каким способом Вы употребляли наркотические или токсические вещества (назвать то, что клиент отвечал на вопрос 3.8.)?'),
        ),
        migrations.AlterField(
            model_name='typologicalgroup',
            name='group',
            field=models.IntegerField(choices=[(0, 'Клиент не может быть относен к типологической группе потребителей ПАВ'), (1, 'Группа 1 «Женщины, активно употребляющие ПАВ, противопоставляющие себя социуму»'), (2, 'Группа 2 «Женщины, употребляющие ПАВ с более развитым коммуникативным потенциалом»')], verbose_name='Основная типологическая группа'),
        ),
        migrations.AlterField(
            model_name='typologicalgroup',
            name='subgroup',
            field=models.IntegerField(blank=True, choices=[(1, 'Группа 2.1 «Молодые женщины с социально-бытовыми проблемами в период неактивного употребления ПАВ»'), (2, 'Группа 2.2 «Женщины с длительным стажем употребления ПАВ и сопутствующими социально-медицинскими проблемами»')], null=True, verbose_name='Подгруппа типологической группы 2'),
        ),
    ]
