# Generated by Django 3.0.8 on 2020-08-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0003_auto_20200824_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asocialbehavior',
            name='frequencyOfAlcoholUse',
            field=models.IntegerField(blank=True, choices=[(1, 'ежедневно'), (2, 'раз в два-три дня'), (3, 'раз в неделю'), (4, 'раз в месяц'), (5, 'реже одного раза в месяц')], null=True, verbose_name='Частота употребления алкоголя'),
        ),
    ]
