# Generated by Django 3.1.2 on 2020-12-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0003_auto_20201110_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherFamilyMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_is', models.TextField(blank=True, null=True, verbose_name='Кем приходится')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_center_app.client')),
            ],
            options={
                'verbose_name': 'Сведения о других членах семьи',
                'verbose_name_plural': 'Сведения о других членах семьи',
            },
        ),
    ]
