# Generated by Django 3.0.8 on 2020-07-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0003_auto_20200716_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='child',
            name='birthdate',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='child',
            name='documents',
            field=models.IntegerField(choices=[(1, 'да'), (2, 'нет')], verbose_name='Наличие документов у ребенка'),
        ),
        migrations.AlterField(
            model_name='child',
            name='educate_child',
            field=models.IntegerField(choices=[(1, 'да'), (2, 'нет'), (3, 'подписала временный отказ'), (4, 'подписала полный отказ'), (5, 'ушла из родильного дома'), (6, 'собирается подписывать временный отказ'), (7, 'собирается подписывать полный отказ')], verbose_name='Планирует ли воспитывать ребенка'),
        ),
        migrations.AlterField(
            model_name='child',
            name='education',
            field=models.IntegerField(choices=[(1, 'да'), (2, 'нет')], verbose_name='Посещает ли образовательное учреждение'),
        ),
        migrations.AlterField(
            model_name='child',
            name='educational_institution',
            field=models.TextField(blank=True, null=True, verbose_name='Какое образовательное учреждение'),
        ),
        migrations.AlterField(
            model_name='child',
            name='fatherhood',
            field=models.IntegerField(choices=[(1, 'да'), (2, 'нет')], verbose_name='Установлено ли отцовство на ребенка'),
        ),
        migrations.AlterField(
            model_name='child',
            name='full_name',
            field=models.TextField(verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='child',
            name='location',
            field=models.IntegerField(choices=[(1, 'в семье'), (2, 'больница'), (3, 'дом ребенка')], verbose_name='Место нахождения ребенка'),
        ),
        migrations.AlterField(
            model_name='child',
            name='reason_refusal',
            field=models.IntegerField(choices=[(1, 'отсутствие жилья'), (2, 'употребление наркотиков'), (3, 'низкая материальная обеспеченность'), (4, 'физическое или психическое заболевание'), (5, 'отсутствие семейной поддержки'), (6, 'нежелательная беременность')], verbose_name='Возможные причины отказа'),
        ),
        migrations.AlterField(
            model_name='child',
            name='sex',
            field=models.IntegerField(choices=[(1, 'мужской'), (2, 'женский')], verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='child',
            name='status',
            field=models.IntegerField(choices=[(1, 'родной'), (2, 'усыновлен'), (3, 'оформлена опека'), (4, 'оставшийся без попечения родителей/лишение родительских прав'), (5, 'сирота'), (6, 'инвалидность')], verbose_name='Статус ребенка'),
        ),
        migrations.AlterField(
            model_name='childallowanceandcompensation',
            name='basis_payments',
            field=models.IntegerField(choices=[(1, 'нет оснований для оформления выплаты'), (2, 'имеется право на выплату'), (3, 'требует оформления'), (4, 'находится в стадии оформления'), (5, 'выплачивается')], verbose_name='Основания для выплаты'),
        ),
        migrations.AlterField(
            model_name='childallowanceandcompensation',
            name='type_benefit_payment',
            field=models.IntegerField(blank=True, choices=[(1, 'единовременная компенсационная выплата при рождении ребенка (СПБ)'), (2, 'единовременное пособие при рождении ребенка (РФ)'), (3, 'ежемесячное пособие на ребёнка в возрасте от рождения до 1 года (СПб)'), (4, 'ежемесячное пособие на ребёнка в возрасте от 1 года до 7 лет (СПб)'), (5, 'ежемесячное пособие на детей школьного возраста (СПб)'), (6, 'пособие по беременности и родам (РФ)'), (7, 'единовременное пособие женщинам, вставшим на учёт в ранние сроки (РФ)'), (8, 'ежемесячное пособие по уходу за ребёнком (РФ)'), (9, 'сертификат на получение материнского (семейного) капитала')], null=True, verbose_name='Вид пособия/компенсационной выплаты'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_phone',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес, телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='boy',
            field=models.TextField(blank=True, null=True, verbose_name='Мал.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='came',
            field=models.TextField(blank=True, null=True, verbose_name='Пришли'),
        ),
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.TextField(blank=True, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='client',
            name='children',
            field=models.TextField(blank=True, null=True, verbose_name='Дети (ФИО)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='client',
            name='criminal_record',
            field=models.TextField(blank=True, null=True, verbose_name='Наличие судимости'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dependence',
            field=models.TextField(blank=True, null=True, verbose_name='Зависимость'),
        ),
        migrations.AlterField(
            model_name='client',
            name='employment',
            field=models.TextField(blank=True, null=True, verbose_name='Трудовая занятость'),
        ),
        migrations.AlterField(
            model_name='client',
            name='girl',
            field=models.TextField(blank=True, null=True, verbose_name='Дев.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='in_window',
            field=models.TextField(blank=True, null=True, verbose_name='В окне'),
        ),
        migrations.AlterField(
            model_name='client',
            name='man',
            field=models.TextField(blank=True, null=True, verbose_name='Муж.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mo',
            field=models.TextField(blank=True, null=True, verbose_name='М/О'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nl',
            field=models.TextField(blank=True, null=True, verbose_name='Н/л'),
        ),
        migrations.AlterField(
            model_name='client',
            name='number_children',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количетсво детей'),
        ),
        migrations.AlterField(
            model_name='client',
            name='number_vz',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество вз'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.TextField(blank=True, null=True, verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='client',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата постановки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state_dependence',
            field=models.TextField(blank=True, null=True, verbose_name='Состояние зависимости'),
        ),
        migrations.AlterField(
            model_name='client',
            name='support',
            field=models.TextField(blank=True, null=True, verbose_name='Какое сопровождение'),
        ),
        migrations.AlterField(
            model_name='client',
            name='undefined',
            field=models.TextField(blank=True, null=True, verbose_name='Неопределен'),
        ),
        migrations.AlterField(
            model_name='client',
            name='woman',
            field=models.TextField(blank=True, null=True, verbose_name='Жен.'),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='basis_facilities',
            field=models.IntegerField(choices=[(1, 'да'), (2, 'нет')], verbose_name='Основания для льгот'),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина,по которой не оформлены льготы'),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='right_facilities',
            field=models.IntegerField(choices=[(1, 'да'), (2, 'нет')], verbose_name='Имеет право на льготы (указать)'),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='stage_registration_facilities',
            field=models.IntegerField(blank=True, choices=[(1, 'оформлено полностью'), (2, 'частично оформлено'), (3, 'в стадии оформления'), (4, 'не оформлено')], null=True, verbose_name='Стадия оформления льгот'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='dod',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='sex',
            field=models.IntegerField(choices=[(1, 'мужской'), (2, 'женский')], verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='workPlace',
            field=models.IntegerField(choices=[(1, 'постоянное'), (2, 'временное'), (3, 'эпизодическое'), (4, 'не работает'), (5, 'состоит в центре занятости населения в качестве безработного')], verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='healthchild',
            name='center_aids',
            field=models.IntegerField(choices=[(1, 'да'), (2, 'нет')], verbose_name='Учет в центре СПИД'),
        ),
        migrations.AlterField(
            model_name='healthchild',
            name='center_prevention',
            field=models.IntegerField(choices=[(1, 'да'), (2, 'нет')], verbose_name='Учет в лечебно-профилактическом учреждении района'),
        ),
        migrations.AlterField(
            model_name='healthchild',
            name='health',
            field=models.IntegerField(choices=[(1, 'да'), (2, 'нет')], verbose_name='Ребенок родился здоровым'),
        ),
        migrations.AlterField(
            model_name='healthchild',
            name='hiv_plus',
            field=models.IntegerField(choices=[(1, 'да'), (2, 'нет')], verbose_name='Родился после установления ВИЧ-положительного статуса клиента'),
        ),
        migrations.AlterField(
            model_name='healthchild',
            name='hiv_prevention',
            field=models.IntegerField(choices=[(1, 'во время родов'), (2, 'после родов'), (3, 'не знает')], verbose_name='Получал ли профилактику ВИЧ'),
        ),
        migrations.AlterField(
            model_name='healthchild',
            name='with_mother',
            field=models.IntegerField(choices=[(1, 'да'), (2, 'нет')], verbose_name='Ребенок выписан из родильного отделения вместе с матерью'),
        ),
        migrations.AlterField(
            model_name='healthchild',
            name='withdrawal_symptoms',
            field=models.IntegerField(choices=[(1, 'да'), (2, 'нет')], verbose_name='В абстинентном синдроме'),
        ),
        migrations.AlterField(
            model_name='socialeconomiccondition',
            name='client_security',
            field=models.IntegerField(blank=True, choices=[(1, 'достаточное с учетом возраста и потребностей ребенка'), (2, 'удовлетворительное'), (3, 'недостаточное')], null=True, verbose_name='Обеспеченность клиентки и ее детей полноценным питанием,одеждой,обувью,предметами личной гигиены'),
        ),
        migrations.AlterField(
            model_name='socialeconomiccondition',
            name='income_confirmation',
            field=models.IntegerField(blank=True, choices=[(1, 'возможно подтвердить документально'), (2, 'необходим сбор документов'), (3, 'невозможно подтвердить документально')], null=True, verbose_name='Возможность подтверждения дохода ниже прожиточного минимума'),
        ),
        migrations.AlterField(
            model_name='socialeconomiccondition',
            name='income_level',
            field=models.IntegerField(choices=[(1, 'высокий уровень'), (2, 'около двух прожиточных минимумов на человека'), (3, 'на уровне прожиточного минимума'), (4, 'ниже прожиточного минимума'), (5, 'нет дохода')], verbose_name='Уровень доходов клиента'),
        ),
        migrations.AlterField(
            model_name='sociallivingcondition',
            name='amount_debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Сумма задолженности (в рублях)'),
        ),
        migrations.AlterField(
            model_name='sociallivingcondition',
            name='ownership',
            field=models.IntegerField(blank=True, choices=[(1, 'договор по найму жилья'), (2, 'договор аренды'), (3, 'собственность клиента')], null=True, verbose_name='Право собственности,владения и пользования'),
        ),
        migrations.AlterField(
            model_name='sociallivingcondition',
            name='payment',
            field=models.IntegerField(blank=True, choices=[(1, 'своевременно в полном объеме'), (2, 'незначительная задолженность'), (3, 'значительная задолженность'), (4, 'начилие задолженности по алиментам/кредиту')], null=True, verbose_name='Оплата за жилье и коммунальные услуги'),
        ),
        migrations.AlterField(
            model_name='sociallivingcondition',
            name='room_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Жилая площадь в расчете на человека (кв.м.)'),
        ),
        migrations.AlterField(
            model_name='sociallivingcondition',
            name='sanitary_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'хорошее'), (2, 'удовлетворительное'), (3, 'антисанитарное'), (4, 'признаки аварийности жилого помещения')], null=True, verbose_name='Санитарно-гигиеническое и техническое состояние жилого помещения'),
        ),
        migrations.AlterField(
            model_name='sociallivingcondition',
            name='type_room',
            field=models.IntegerField(choices=[(1, 'жилой дом'), (2, 'отдельная квартира'), (3, 'комната в коммунальной квартире'), (4, 'комната в общежитии'), (5, 'отсутствует')], verbose_name='Вид жилого помещения'),
        ),
        migrations.AlterField(
            model_name='socialpayment',
            name='basis_social_payments',
            field=models.IntegerField(choices=[(1, 'нет оснований для оформления выплаты'), (2, 'имеется право на выплату'), (3, 'требует оформления'), (4, 'находится в стадии оформления'), (5, 'выплачивается')], verbose_name='Основания для соациальных выплат'),
        ),
        migrations.AlterField(
            model_name='socialpayment',
            name='pension',
            field=models.IntegerField(blank=True, choices=[(1, 'по старости'), (2, 'по потере кормильца'), (3, 'по инвалидности')], null=True, verbose_name='Пенсия'),
        ),
        migrations.AlterField(
            model_name='socialpayment',
            name='type_social_payment',
            field=models.IntegerField(blank=True, choices=[(1, 'единовременные выплаты'), (2, 'ежемесячные выплаты'), (3, 'государственная социальная помощь,доплата до прожиточного минимума'), (4, 'государственная социальная помощь в трудной жизненной ситуации')], null=True, verbose_name='Вид социальной выплаты'),
        ),
        migrations.AlterField(
            model_name='sourceincome',
            name='alimony',
            field=models.IntegerField(choices=[(1, 'да'), (2, 'нет')], verbose_name='Алименты/нотариальное соглашение о содержании ребенка'),
        ),
        migrations.AlterField(
            model_name='sourceincome',
            name='benefits',
            field=models.IntegerField(choices=[(1, 'да'), (2, 'нет')], verbose_name='Льготы по коммунальным услугам'),
        ),
        migrations.AlterField(
            model_name='sourceincome',
            name='material_means',
            field=models.IntegerField(blank=True, choices=[(1, 'родственниками'), (2, 'партнером'), (3, 'мужем')], null=True, verbose_name='Предоставление материальных средств'),
        ),
        migrations.AlterField(
            model_name='sourceincome',
            name='rent',
            field=models.IntegerField(blank=True, choices=[(1, 'комнаты'), (2, 'оборудования'), (3, 'участка')], null=True, verbose_name='Сдача в аренду'),
        ),
        migrations.AlterField(
            model_name='sourceincome',
            name='salary',
            field=models.IntegerField(blank=True, choices=[(1, 'постоянно'), (2, 'переодически'), (3, 'редко')], null=True, verbose_name='Заработная плата'),
        ),
    ]
