# Generated by Django 3.1.2 on 2020-10-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0003_auto_20201024_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='husbandinformation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_center_app.client'),
        ),
    ]
