# Generated by Django 3.1.2 on 2020-10-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0004_auto_20201024_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronicdisease',
            name='reasonForNotGettingTreatment',
            field=models.TextField(blank=True, null=True, verbose_name='Причина, по которой не получает лечение ВИЧ'),
        ),
    ]
