# Generated by Django 3.0.8 on 2020-07-23 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0005_auto_20200721_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembersinformation',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_center_app.Client'),
        ),
    ]
