# Generated by Django 3.1.2 on 2020-10-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0005_auto_20201024_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='addressApNum',
        ),
        migrations.RemoveField(
            model_name='client',
            name='addressCity',
        ),
        migrations.RemoveField(
            model_name='client',
            name='addressHouseNum',
        ),
        migrations.RemoveField(
            model_name='client',
            name='addressIndex',
        ),
        migrations.RemoveField(
            model_name='client',
            name='addressStreet',
        ),
        migrations.RemoveField(
            model_name='client',
            name='municipalDistrict',
        ),
        migrations.AddField(
            model_name='client',
            name='actualAddressApNum',
            field=models.TextField(blank=True, null=True, verbose_name='Номер квартиры (АФП)'),
        ),
        migrations.AddField(
            model_name='client',
            name='actualAddressCity',
            field=models.TextField(blank=True, null=True, verbose_name='Населенный пункт (АФП)'),
        ),
        migrations.AddField(
            model_name='client',
            name='actualAddressHouseNum',
            field=models.TextField(blank=True, null=True, verbose_name='Дом (АФП)'),
        ),
        migrations.AddField(
            model_name='client',
            name='actualAddressIndex',
            field=models.IntegerField(blank=True, null=True, verbose_name='Почтовый индекс (АФП)'),
        ),
        migrations.AddField(
            model_name='client',
            name='actualAddressStreet',
            field=models.TextField(blank=True, null=True, verbose_name='Улица (АФП)'),
        ),
        migrations.AddField(
            model_name='client',
            name='actualMunicipalDistrict',
            field=models.IntegerField(blank=True, choices=[(1, 'Юго-Запад'), (2, 'Южно-Приморский'), (3, 'Сосновая Поляна'), (4, 'Урицк'), (5, 'Константиновское'), (6, 'Горелово'), (7, 'г.Красное Село')], null=True, verbose_name='Муниципальный округ (АФП)'),
        ),
        migrations.AddField(
            model_name='client',
            name='registrationAddressApNum',
            field=models.TextField(blank=True, null=True, verbose_name='Номер квартиры (АР)'),
        ),
        migrations.AddField(
            model_name='client',
            name='registrationAddressCity',
            field=models.TextField(blank=True, null=True, verbose_name='Населенный пункт (АР)'),
        ),
        migrations.AddField(
            model_name='client',
            name='registrationAddressHouseNum',
            field=models.TextField(blank=True, null=True, verbose_name='Дом (АР)'),
        ),
        migrations.AddField(
            model_name='client',
            name='registrationAddressIndex',
            field=models.IntegerField(blank=True, null=True, verbose_name='Почтовый индекс (АР)'),
        ),
        migrations.AddField(
            model_name='client',
            name='registrationAddressStreet',
            field=models.TextField(blank=True, null=True, verbose_name='Улица (АР)'),
        ),
        migrations.AddField(
            model_name='client',
            name='registrationMunicipalDistrict',
            field=models.IntegerField(blank=True, choices=[(1, 'Юго-Запад'), (2, 'Южно-Приморский'), (3, 'Сосновая Поляна'), (4, 'Урицк'), (5, 'Константиновское'), (6, 'Горелово'), (7, 'г.Красное Село')], null=True, verbose_name='Муниципальный округ (АР)'),
        ),
    ]
