# Generated by Django 3.0.8 on 2020-08-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0005_auto_20200830_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='husbandinformation',
            name='alcoholUse',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Употребление алкоголя'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='durationOfUse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Длительность употребления (в годах)'),
        ),
    ]
