# Generated by Django 3.0.8 on 2020-10-10 12:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0007_auto_20200928_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='center_prevention',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address_phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='boy',
        ),
        migrations.RemoveField(
            model_name='client',
            name='came',
        ),
        migrations.RemoveField(
            model_name='client',
            name='category',
        ),
        migrations.RemoveField(
            model_name='client',
            name='children',
        ),
        migrations.RemoveField(
            model_name='client',
            name='criminal_record',
        ),
        migrations.RemoveField(
            model_name='client',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='client',
            name='girl',
        ),
        migrations.RemoveField(
            model_name='client',
            name='hiv_status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='in_window',
        ),
        migrations.RemoveField(
            model_name='client',
            name='man',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mo',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nl',
        ),
        migrations.RemoveField(
            model_name='client',
            name='number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='number_children',
        ),
        migrations.RemoveField(
            model_name='client',
            name='number_vz',
        ),
        migrations.RemoveField(
            model_name='client',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='client',
            name='production_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='question',
        ),
        migrations.RemoveField(
            model_name='client',
            name='state_dependence',
        ),
        migrations.RemoveField(
            model_name='client',
            name='support',
        ),
        migrations.RemoveField(
            model_name='client',
            name='undefined',
        ),
        migrations.RemoveField(
            model_name='client',
            name='vzr',
        ),
        migrations.RemoveField(
            model_name='client',
            name='woman',
        ),
        migrations.RemoveField(
            model_name='husbandinformation',
            name='disabilityGroup',
        ),
        migrations.RemoveField(
            model_name='husbandinformation',
            name='professionalEducation',
        ),
        migrations.RemoveField(
            model_name='husbandinformation',
            name='specialSocialStatus',
        ),
        migrations.RemoveField(
            model_name='sociallivingcondition',
            name='amount_debt',
        ),
        migrations.AddField(
            model_name='asocialbehavior',
            name='wherePsyRehWasA',
            field=models.TextField(blank=True, null=True, verbose_name='Где проходил реабилитацию(алкоголь)?'),
        ),
        migrations.AddField(
            model_name='asocialbehavior',
            name='wherePsyRehWasD',
            field=models.TextField(blank=True, null=True, verbose_name='Где проходил реабилитацию(наркотики)?'),
        ),
        migrations.AddField(
            model_name='client',
            name='aboutNoWork',
            field=models.TextField(blank=True, null=True, verbose_name='Причина, по которой не работает'),
        ),
        migrations.AddField(
            model_name='client',
            name='aboutWork',
            field=models.TextField(blank=True, null=True, verbose_name='Где, кем работает (при наличии работы)'),
        ),
        migrations.AddField(
            model_name='client',
            name='addressApNum',
            field=models.TextField(blank=True, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AddField(
            model_name='client',
            name='addressCity',
            field=models.TextField(blank=True, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AddField(
            model_name='client',
            name='addressHouseNum',
            field=models.TextField(blank=True, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='client',
            name='addressIndex',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)], verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='client',
            name='addressStreet',
            field=models.TextField(blank=True, null=True, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='client',
            name='adultsCount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во взрослых'),
        ),
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='client',
            name='avDoc',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Наличие документов'),
        ),
        migrations.AddField(
            model_name='client',
            name='cityzenship',
            field=models.IntegerField(blank=True, choices=[(1, 'Россия'), (2, 'страна СНГ')], null=True, verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='client',
            name='contractNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='client',
            name='dateOfCertified',
            field=models.DateField(blank=True, null=True, verbose_name='Дата постановки на учет'),
        ),
        migrations.AddField(
            model_name='client',
            name='dateOfInterview',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения интервью'),
        ),
        migrations.AddField(
            model_name='client',
            name='disability',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Инвалидность'),
        ),
        migrations.AddField(
            model_name='client',
            name='dod',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='client',
            name='education',
            field=models.IntegerField(blank=True, choices=[(1, 'высшее'), (2, 'неоконченное высшее'), (3, 'среднее специальное'), (4, 'начальное профессиональное'), (5, 'обучается'), (6, 'полное среднее (11 классов)'), (7, 'общее среднее (9 классов)'), (8, 'неоконченное общее среднее'), (9, 'начальная школа')], null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='client',
            name='familiesCategory',
            field=models.IntegerField(blank=True, choices=[(1, 'полная семья'), (2, 'одинокий родитель'), (3, 'многодетная семья'), (4, 'разведённые'), (5, 'беженцы / переселенцы'), (6, 'несовершеннолетние родители'), (7, 'замещающая семья'), (8, 'семья с инвалидом'), (9, 'другое')], null=True, verbose_name='Категория семей'),
        ),
        migrations.AddField(
            model_name='client',
            name='formOfReferral',
            field=models.IntegerField(blank=True, choices=[(1, 'самообращение'), (2, 'КДН и ЗП'), (3, 'органы опеки и попечительства'), (4, 'образовательные учреждения'), (5, 'дом ребёнка'), (6, 'родильный дом'), (7, 'женская консультация'), (8, 'детская поликлиника'), (9, 'центр СПИД'), (10, 'отдел полиции'), (11, 'УФСИН'), (12, 'перевод'), (13, 'СО НКО')], null=True, verbose_name='Форма обращения'),
        ),
        migrations.AddField(
            model_name='client',
            name='minorsCount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во несовершеннолетних'),
        ),
        migrations.AddField(
            model_name='client',
            name='municipalDistrict',
            field=models.IntegerField(blank=True, choices=[(1, 'Юго-Запад'), (2, 'Южно-Приморский'), (3, 'Сосновая Поляна'), (4, 'Урицк'), (5, 'Константиновское'), (6, 'Горелово'), (7, 'г.Красное Сел')], null=True, verbose_name='Муниципальный округ'),
        ),
        migrations.AddField(
            model_name='client',
            name='passDateIssue',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='client',
            name='passFromWhomIssue',
            field=models.TextField(blank=True, null=True, verbose_name='Выдан'),
        ),
        migrations.AddField(
            model_name='client',
            name='passNumber',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)], verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='client',
            name='passSeries',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)], verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='client',
            name='phoneNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='client',
            name='placeOfRegistration',
            field=models.IntegerField(blank=True, choices=[(1, 'Санкт-Петербург'), (2, 'Ленинградская область'), (3, 'другой регион РФ'), (4, 'страна СНГ')], null=True, verbose_name='Место регистрации'),
        ),
        migrations.AddField(
            model_name='client',
            name='registration',
            field=models.IntegerField(blank=True, choices=[(1, 'постоянная'), (2, 'временная')], null=True, verbose_name='Регистрация'),
        ),
        migrations.AddField(
            model_name='client',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'мужской'), (2, 'женский')], null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='client',
            name='stateOfDependence',
            field=models.IntegerField(blank=True, choices=[(1, 'активное потребление'), (2, 'ремиссия')], null=True, verbose_name='Состояние зависимости'),
        ),
        migrations.AddField(
            model_name='client',
            name='workPlace',
            field=models.IntegerField(blank=True, choices=[(1, 'постоянное'), (2, 'временное'), (3, 'эпизодическое'), (4, 'не работает'), (5, 'состоит в центре занятости населения в качестве безработного')], null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='husbandinformation',
            name='categoryFamilies',
            field=models.IntegerField(blank=True, choices=[(1, 'полная семья'), (2, 'одинокий родитель'), (3, 'многодетная семья'), (4, 'разведённые'), (5, 'беженцы/переселенцы'), (6, 'несовершеннолетние родители'), (7, 'замещающая семья'), (8, 'семья с инвалидом'), (9, 'другое')], null=True, verbose_name='Категория семей'),
        ),
        migrations.AddField(
            model_name='husbandinformation',
            name='disability',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='asocialbehavior',
            name='accountingInODN_RUVD',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет'), (3, 'не знаю')], null=True, verbose_name='Состоит на учёте в ОДН РУВД'),
        ),
        migrations.AlterField(
            model_name='asocialbehavior',
            name='criminalRecord',
            field=models.IntegerField(blank=True, choices=[(1, 'условная'), (2, 'отсрочка приговора'), (3, 'из мест лишения свободы'), (4, 'под следствием'), (5, 'нет')], null=True, verbose_name='Наличие судимости'),
        ),
        migrations.AlterField(
            model_name='asocialbehavior',
            name='theTreatmentWasA',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет'), (3, 'химическая защита')], null=True, verbose_name='Проходил ли лечение(алкоголь)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='hiv_prevention',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет'), (3, 'не знаю')], null=True, verbose_name='Получал ли профилактику ВИЧ'),
        ),
        migrations.AlterField(
            model_name='child',
            name='location',
            field=models.IntegerField(blank=True, choices=[(1, 'в семье'), (2, 'больница'), (3, 'социальное учреждение')], null=True, verbose_name='Место нахождения ребенка'),
        ),
        migrations.AlterField(
            model_name='chronicdisease',
            name='doesCenterVisitAIDS',
            field=models.IntegerField(blank=True, choices=[(1, 'раз в 3 месяца'), (2, 'раз в полгода'), (3, 'раз в год'), (4, 'нет')], null=True, verbose_name='Посещает ли центр СПИД'),
        ),
        migrations.AlterField(
            model_name='chronicdisease',
            name='estimatedTimeOfInfection',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Когда узнал о диагнозе (в годах)'),
        ),
        migrations.AlterField(
            model_name='chronicdisease',
            name='receivedChemoprophylaxis',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Получал ли химиопрофилактику'),
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='Код клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dependence',
            field=models.IntegerField(blank=True, choices=[(1, 'алкогольная'), (2, 'наркотическая'), (3, 'созависимость')], null=True, verbose_name='Зависимость'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='education',
            field=models.IntegerField(blank=True, choices=[(1, 'высшее'), (2, 'неоконченное высшее'), (3, 'среднее специальное'), (4, 'начальное профессиональное'), (5, 'обучается'), (6, 'полное среднее (11 классов)'), (7, 'общее среднее (9 классов)'), (8, 'неоконченное общее среднее'), (9, 'начальная школа')], null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='husband',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_center_app.FamilyMembersInformation'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='theTreatmentWasA',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет'), (3, 'химическая защита')], null=True, verbose_name='Проходил ли лечение(алкоголь)'),
        ),
        migrations.AlterField(
            model_name='sociallivingcondition',
            name='ownership',
            field=models.IntegerField(blank=True, choices=[(1, 'договор по найму жилья'), (2, 'собственность клиента')], null=True, verbose_name='Право собственности,владения и пользования'),
        ),
        migrations.AlterField(
            model_name='sociallivingcondition',
            name='payment',
            field=models.IntegerField(blank=True, choices=[(1, 'своевременно в полном объеме'), (2, 'незначительная задолженность'), (3, 'значительная задолженность')], null=True, verbose_name='Оплата за жилье и коммунальные услуги'),
        ),
        migrations.AlterField(
            model_name='sociallivingcondition',
            name='room_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Жилая площадь (кв.м.)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.DeleteModel(
            name='GeneralInformation',
        ),
    ]
