# Generated by Django 3.0.8 on 2020-07-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0008_auto_20200728_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='husbandinformation',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='asocialbehavior',
            name='durationOfRemissionA',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Длительность ремиссии (в годах)(алкоголь)'),
        ),
        migrations.AlterField(
            model_name='asocialbehavior',
            name='durationOfRemissionD',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Длительность ремиссии (в годах)(наркотики)'),
        ),
        migrations.AlterField(
            model_name='asocialbehavior',
            name='durationOfUse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Длительность употрбления (в годах)'),
        ),
        migrations.AlterField(
            model_name='chronicdisease',
            name='estimatedTimeOfInfection',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Предположительное время инфицирования (в годах)'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='durationOfRemissionA',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Длительность ремиссии (в годах)(алкоголь)'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='durationOfRemissionD',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Длительность ремиссии (в годах)(наркотики)'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='durationOfUse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Длительность употрбления (в годах)'),
        ),
    ]
