# Generated by Django 3.0.8 on 2020-10-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0008_auto_20201010_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembersinformation',
            name='withWhomLiving',
            field=models.IntegerField(blank=True, choices=[(1, 'со своими родителями'), (2, 'с родителями партнёра'), (5, 'с семьёй'), (6, 'с родственниками')], null=True, verbose_name='С кем проживает'),
        ),
    ]
