# Generated by Django 3.0.8 on 2020-07-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0009_auto_20200728_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='reason_refusal',
            field=models.IntegerField(blank=True, choices=[(1, 'отсутствие жилья'), (2, 'употребление наркотиков'), (3, 'низкая материальная обеспеченность'), (4, 'физическое или психическое заболевание'), (5, 'отсутствие семейной поддержки'), (6, 'нежелательная беременность')], null=True, verbose_name='Возможные причины отказа'),
        ),
    ]
