# Generated by Django 3.0.8 on 2020-10-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0009_auto_20201010_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phoneNumber',
            field=models.TextField(blank=True, max_length=15, null=True, verbose_name='Номер телефона'),
        ),
    ]
