# Generated by Django 3.0.8 on 2020-07-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0010_auto_20200729_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthchild',
            name='hiv_plus',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Родился после установления ВИЧ-положительного статуса клиента'),
        ),
        migrations.AlterField(
            model_name='healthchild',
            name='hiv_prevention',
            field=models.IntegerField(blank=True, choices=[(1, 'во время родов'), (2, 'после родов'), (3, 'не знает')], null=True, verbose_name='Получал ли профилактику ВИЧ'),
        ),
    ]
