# Generated by Django 3.0.8 on 2020-10-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0010_auto_20201010_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contractNumber',
            field=models.TextField(blank=True, null=True, verbose_name='Номер договора'),
        ),
    ]
