# Generated by Django 3.0.8 on 2020-07-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0011_auto_20200730_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='husbandinformation',
            name='specialSocialStatus',
            field=models.IntegerField(choices=[(1, 'инвалидность'), (2, 'многодетная семья'), (3, 'одинокая мать'), (4, 'лицо из числа детей сирот и детей, оставшихся без попечения родителей')], verbose_name='Особый социальный статус'),
        ),
    ]
