# Generated by Django 3.0.8 on 2020-07-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0012_auto_20200730_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='husbandinformation',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='fullName',
            field=models.TextField(verbose_name='ФИО мужа/партнёра'),
        ),
    ]
