# Generated by Django 3.0.8 on 2020-07-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0014_auto_20200730_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpayment',
            name='basis_social_payments',
            field=models.IntegerField(choices=[(1, 'нет оснований для оформления выплаты'), (2, 'имеется право на выплату'), (3, 'требует оформления'), (4, 'находится в стадии оформления'), (5, 'выплачивается')], verbose_name='Основания для социальных выплат'),
        ),
    ]
