# Generated by Django 3.0.8 on 2020-07-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0015_auto_20200731_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertopinion',
            name='otherInformation',
            field=models.TextField(blank=True, null=True, verbose_name='Другие сведения о клиенте и членах семьи, сообщённые во время диагностического интервью'),
        ),
    ]
