# Generated by Django 3.0.8 on 2020-08-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0019_auto_20200807_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretationgage',
            name='risk_abuse',
            field=models.IntegerField(choices=[(0, 'выраженные признаки потребления не определяются'), (3, 'выраженные признаки злоупотребления')], verbose_name='Риск злоупотребления'),
        ),
        migrations.AlterField(
            model_name='interpretationgage',
            name='risk_dependency',
            field=models.IntegerField(choices=[(0, 'выраженные признаки зависимости не определяются'), (2, 'имеются признаки зависимости')], verbose_name='Риск зависимости'),
        ),
    ]
