# Generated by Django 3.0.8 on 2020-08-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0020_auto_20200807_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskdependency',
            name='test',
        ),
        migrations.AddField(
            model_name='testgage',
            name='company',
            field=models.IntegerField(blank=True, choices=[(1, 'В компании'), (2, 'В одиночку')], null=True, verbose_name='3.12. употребляли ли Вы вещества, меняющие настроение, один или в компании?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='difficulties',
            field=models.IntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True, verbose_name='3.10. Бывали ли трудности на работе или в личных отношениях, когда Вы были под действием веществ или  потому, что другие люди были слишком обеспокоены Вашей увлеченностью наркотическим веществом?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='do_not_work',
            field=models.IntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True, verbose_name='3.2. Бывали ли в Вашей жизни ситуации, когда Вы не могли выйти на работу из-за похмелья или состояния опьянения?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='do_not_work_when',
            field=models.IntegerField(blank=True, choices=[(0, 'Больше года назад'), (1, 'Меньше года назад')], null=True, verbose_name='3.2.1. Когда последний раз?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='dose_reduction',
            field=models.IntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True, verbose_name='4.1. Вы думали когда-нибудь о том, чтобы уменьшить  количество употребляемого алкоголя (наркотических веществ)?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='drink_alcohol_time',
            field=models.IntegerField(blank=True, choices=[(0, 'Реже одного раза в неделю'), (1, 'Чаще одного раза в неделю'), (2, 'Каждый день или «почти каждый день»')], null=True, verbose_name='3.7. Как часто Вы пьете алкогольные напитки, хотя бы чуть-чуть?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='fault',
            field=models.IntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True, verbose_name='4.3. Вы испытывали когда-нибудь чувство вины по поводу того, что слишком много или долго употребляли алкоголь (наркотики)?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='fight',
            field=models.IntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True, verbose_name='3.4. Бывало ли, что Вы вступали в драку или Вас били, когда Вы были в состоянии алкогольного опьянения?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='how_use',
            field=models.IntegerField(blank=True, choices=[(1, 'Курил, нюхал, глотал'), (2, 'Внутримышечные инъекции'), (3, 'Внутривенные инъекции')], null=True, verbose_name='3.9. Каким способом Вы употребляли наркотические или токсические вещества (назвать то, что клиент отвечал на вопрос 3.8.)?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='injuries',
            field=models.IntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Травмы серьезнее синяков'), (3, 'Попадал в больницу из-за травм, полученных в состоянии опьянения')], null=True, verbose_name='3.5. Получали ли Вы травмы в состоянии алкогольного опьянения?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='irritation',
            field=models.IntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True, verbose_name='4.2. Вас раздражает, если люди критикуют Вас за употребление алкоголя (употребление наркотиков)?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='loss_documents',
            field=models.IntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True, verbose_name='3.1. Бывали ли в Вашей жизни ситуации, когда вы теряли документы и(или) деньги, когда выпьете или употребите другие вещества, меняющие состояние?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='loss_documents_time',
            field=models.IntegerField(blank=True, choices=[(0, 'Один раз'), (2, 'Больше одного')], null=True, verbose_name='3.1.2. Было ли такое один раз в вашей жизни?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='loss_documents_when',
            field=models.IntegerField(blank=True, choices=[(0, 'Больше года назад'), (1, 'За последний год ')], null=True, verbose_name='3.1.1. Когда последний раз?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='loss_loved_ones',
            field=models.IntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True, verbose_name='3.3. Теряли ли Вы отношения с друзьями или любовные, потому что Ваш друг или партнер были недовольны вашими отношениями с алкоголем?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='lots_alcohol',
            field=models.IntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True, verbose_name='3.6. Бывало ли, что Вы выпивали больше полбутылки водки, или бутылки вина или полутора литров пива за один раз (за один вечер)?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='lots_alcohol_time',
            field=models.IntegerField(blank=True, choices=[(0, 'Менее одного раза в полгода'), (1, 'Более одного раза в полгода, реже раза в неделю'), (2, 'Каждую неделю'), (3, 'Каждый день')], null=True, verbose_name='3.6.1. Как часто такое случается?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='poor_health',
            field=models.IntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да'), (3, 'Да, требовалась медицинская помощь')], null=True, verbose_name='3.11. Бывало ли, что Вы себя плохо чувствовали после употребления наркотического вещества (в момент опьянения или после выхода) (сильное сердцебиение, слабость, головная боль, тошнота, дискомфорт в ЖКТ)?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='tone',
            field=models.IntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True, verbose_name='4.4. Вы когда-нибудь употребляли алкоголь (наркотические вещества) для поднятия тонуса утром или с похмелья?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='try_substances',
            field=models.TextField(blank=True, null=True, verbose_name='3.8. Какие вещества, влияющие на настроение и изменяющие сознание, кроме алкоголя Вы пробовали?'),
        ),
        migrations.AddField(
            model_name='testgage',
            name='try_substances_choice',
            field=models.IntegerField(blank=True, choices=[(1, 'Одно наименование'), (2, 'Два и более наименований')], null=True, verbose_name='Какое количество наименований?'),
        ),
        migrations.AlterField(
            model_name='interpretationgage',
            name='risk_abuse',
            field=models.IntegerField(choices=[(0, 'выраженные признаки злоупотребления не определяются'), (3, 'выраженные признаки злоупотребления')], verbose_name='Риск злоупотребления'),
        ),
        migrations.AlterField(
            model_name='testgage',
            name='alcohol',
            field=models.IntegerField(choices=[(0, 'Нет'), (1, 'Да')], verbose_name='1. Злоупотребляли ли Вы алкоголем?'),
        ),
        migrations.DeleteModel(
            name='RiskAbuse',
        ),
        migrations.DeleteModel(
            name='RiskDependency',
        ),
    ]
