# Generated by Django 3.0.8 on 2020-08-09 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0021_auto_20200808_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypologicalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(choices=[(0, 'Не может быть относен к типологической группе потребителей ПАВ'), (1, 'Группа 1'), (2, 'Группа 2')], verbose_name='Основная типологическая группа')),
                ('subgroup', models.IntegerField(blank=True, choices=[(0, 'Не может быть относен к типологической группе потребителей ПАВ'), (1, 'Группа 1'), (2, 'Группа 2')], null=True, verbose_name='Подгруппа типологической группы 2')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_center_app.Client')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_center_app.TestBoyko')),
            ],
        ),
    ]
