# Generated by Django 3.0.8 on 2020-08-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0022_typologicalgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typologicalgroup',
            options={'verbose_name': 'Типологическая группа', 'verbose_name_plural': 'Типологические группы'},
        ),
    ]
