# Generated by Django 3.0.8 on 2020-08-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0023_auto_20200809_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typologicalgroup',
            name='subgroup',
            field=models.IntegerField(blank=True, choices=[(0, 'Не может быть относен к типологической подгруппе группы 2'), (1, 'Группа 2.1'), (2, 'Группа 2.2')], null=True, verbose_name='Подгруппа типологической группы 2'),
        ),
    ]
