# Generated by Django 3.0.8 on 2020-08-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0024_auto_20200809_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typologicalgroup',
            name='subgroup',
            field=models.IntegerField(blank=True, choices=[(1, 'Группа 2.1'), (2, 'Группа 2.2')], null=True, verbose_name='Подгруппа типологической группы 2'),
        ),
    ]
