# Generated by Django 3.0.8 on 2020-08-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0025_auto_20200809_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typologicalgroup',
            name='group',
            field=models.IntegerField(choices=[(0, 'Клиент не может быть относен к типологической группе потребителей ПАВ'), (1, 'Группа 1'), (2, 'Группа 2')], verbose_name='Основная типологическая группа'),
        ),
    ]
