# Generated by Django 3.0.8 on 2020-08-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0026_auto_20200809_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='center_aids',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Учет в центре СПИД'),
        ),
        migrations.AddField(
            model_name='child',
            name='center_prevention',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Учет в лечебно-профилактическом учреждении района'),
        ),
        migrations.AddField(
            model_name='child',
            name='health',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Ребенок родился здоровым'),
        ),
        migrations.AddField(
            model_name='child',
            name='hiv_plus',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Родился после установления ВИЧ-положительного статуса клиента'),
        ),
        migrations.AddField(
            model_name='child',
            name='hiv_prevention',
            field=models.IntegerField(blank=True, choices=[(1, 'во время родов'), (2, 'после родов'), (3, 'не знает')], null=True, verbose_name='Получал ли профилактику ВИЧ'),
        ),
        migrations.AddField(
            model_name='child',
            name='hiv_status_child',
            field=models.IntegerField(blank=True, choices=[(1, 'ВИЧ-положительный'), (2, 'ВИЧ-отрицательный'), (3, 'не установлен')], null=True, verbose_name='ВИЧ-статус ребенка'),
        ),
        migrations.AddField(
            model_name='child',
            name='with_mother',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Ребенок выписан из родильного отделения вместе с матерью'),
        ),
        migrations.AddField(
            model_name='child',
            name='withdrawal_symptoms',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='В абстинентном синдроме'),
        ),
        migrations.DeleteModel(
            name='HealthChild',
        ),
    ]
