# Generated by Django 3.0.8 on 2020-08-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0027_auto_20200812_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='child',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='child',
            name='documents',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Наличие документов у ребенка'),
        ),
        migrations.AlterField(
            model_name='child',
            name='educate_child',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет'), (3, 'подписала временный отказ'), (4, 'подписала полный отказ'), (5, 'ушла из родильного дома'), (6, 'собирается подписывать временный отказ'), (7, 'собирается подписывать полный отказ')], null=True, verbose_name='Планирует ли воспитывать ребенка'),
        ),
        migrations.AlterField(
            model_name='child',
            name='education',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Посещает ли образовательное учреждение'),
        ),
        migrations.AlterField(
            model_name='child',
            name='fatherhood',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Установлено ли отцовство на ребенка'),
        ),
        migrations.AlterField(
            model_name='child',
            name='full_name',
            field=models.TextField(blank=True, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='child',
            name='location',
            field=models.IntegerField(blank=True, choices=[(1, 'в семье'), (2, 'больница'), (3, 'дом ребенка')], null=True, verbose_name='Место нахождения ребенка'),
        ),
        migrations.AlterField(
            model_name='child',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'мужской'), (2, 'женский')], null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='child',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'родной'), (2, 'усыновлен'), (3, 'оформлена опека'), (4, 'оставшийся без попечения родителей/лишение родительских прав'), (5, 'сирота'), (6, 'инвалидность')], null=True, verbose_name='Статус ребенка'),
        ),
    ]
