# Generated by Django 3.0.8 on 2020-08-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0028_auto_20200812_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asocialbehavior',
            name='accountingInNarcologicalClinic',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Учёт в наркологическом диспансере'),
        ),
        migrations.AlterField(
            model_name='asocialbehavior',
            name='accountingInODN_RUVD',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет'), (3, 'не знаю')], null=True, verbose_name='Учёт в ОДН РУВД'),
        ),
        migrations.AlterField(
            model_name='asocialbehavior',
            name='alcoholUse',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Употрбление алкоголя'),
        ),
        migrations.AlterField(
            model_name='asocialbehavior',
            name='caseExaminedInKDN_ZP',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет'), (3, 'не знаю')], null=True, verbose_name='Рассматривалось дело на КДН и ЗП'),
        ),
        migrations.AlterField(
            model_name='asocialbehavior',
            name='commercialSexExperience',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Опыт коммерческого секса'),
        ),
        migrations.AlterField(
            model_name='asocialbehavior',
            name='criminalRecord',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Наличие судимости'),
        ),
        migrations.AlterField(
            model_name='asocialbehavior',
            name='drugUse',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Употребление наркотиков'),
        ),
        migrations.AlterField(
            model_name='asocialbehavior',
            name='experienceSexualAbuse',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Опыт сексуального насилия'),
        ),
        migrations.AlterField(
            model_name='asocialbehavior',
            name='physicalAbuseExperience',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Опыт физического насилия'),
        ),
        migrations.AlterField(
            model_name='childallowanceandcompensation',
            name='basis_payments',
            field=models.IntegerField(blank=True, choices=[(1, 'нет оснований для оформления выплаты'), (2, 'имеется право на выплату'), (3, 'требует оформления'), (4, 'находится в стадии оформления'), (5, 'выплачивается')], null=True, verbose_name='Основания для выплаты'),
        ),
        migrations.AlterField(
            model_name='chronicdisease',
            name='HIVStatus',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='ВИЧ-статус'),
        ),
        migrations.AlterField(
            model_name='chronicdisease',
            name='hepatitisC',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Гепатит С'),
        ),
        migrations.AlterField(
            model_name='expertopinion',
            name='expectations',
            field=models.TextField(blank=True, null=True, verbose_name='Ожидания клиента от помощи социальной службы (запрос)'),
        ),
        migrations.AlterField(
            model_name='expertopinion',
            name='personaImpressions',
            field=models.TextField(blank=True, null=True, verbose_name='Личные впечатления специалиста от взаимодействия с клиентом'),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='basis_facilities',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Основания для льгот'),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='right_facilities',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Имеет право на льготы (указать)'),
        ),
        migrations.AlterField(
            model_name='familymembersinformation',
            name='maritalStatus',
            field=models.IntegerField(blank=True, choices=[(1, 'не замужем'), (2, 'замужем'), (3, 'разведена'), (4, 'вдова')], null=True, verbose_name='Семейное положение'),
        ),
        migrations.AlterField(
            model_name='familymembersinformation',
            name='regularPartner',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Постоянный партнёр'),
        ),
        migrations.AlterField(
            model_name='familymembersinformation',
            name='withWhomLiving',
            field=models.IntegerField(blank=True, choices=[(1, 'одна'), (2, 'с детьми'), (3, 'со своими родителями'), (4, 'с родителями мужа/партнёра'), (5, 'с родственниками'), (6, 'с мужем'), (7, 'с партнёром'), (8, 'с друзьями')], null=True, verbose_name='С кем проживает'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='avDoc',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Наличие документов'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='cityzenship',
            field=models.IntegerField(blank=True, choices=[(1, 'Россия'), (2, 'страна СНГ')], null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='dod',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='education',
            field=models.IntegerField(blank=True, choices=[(1, 'полное среднее (11 классов)'), (2, 'общее среднее (9 классов)'), (3, 'неоконченное общее среднее'), (4, 'начальная школа')], null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='placeOfRegistration',
            field=models.IntegerField(blank=True, choices=[(1, 'Санкт-Петербург'), (2, 'Ленинградская область'), (3, 'другой регион РФ'), (4, 'страна СНГ')], null=True, verbose_name='Место регистрации'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='professionalEducation',
            field=models.IntegerField(blank=True, choices=[(1, 'высшее'), (2, 'неоконченное высшее'), (3, 'среднее специальное'), (4, 'начальное профессиональное'), (5, 'отсутствует'), (6, 'обучается')], null=True, verbose_name='Профессиональное образование'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='registration',
            field=models.IntegerField(blank=True, choices=[(1, 'постоянная'), (2, 'временная')], null=True, verbose_name='Регистрация'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'мужской'), (2, 'женский')], null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='workPlace',
            field=models.IntegerField(blank=True, choices=[(1, 'постоянное'), (2, 'временное'), (3, 'эпизодическое'), (4, 'не работает'), (5, 'состоит в центре занятости населения в качестве безработного')], null=True, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='accountingInNarcologicalClinic',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Учёт в наркологическом диспансере'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='alcoholUse',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Употрбление алкоголя'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='avDoc',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Наличие документов'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='cityzenship',
            field=models.IntegerField(blank=True, choices=[(1, 'Россия'), (2, 'страна СНГ')], null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='criminalRecord',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Наличие судимости'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='dod',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='drugUse',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Употребление наркотиков'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='education',
            field=models.IntegerField(blank=True, choices=[(1, 'полное среднее (11 классов)'), (2, 'общее среднее (9 классов)'), (3, 'неоконченное общее среднее'), (4, 'начальная школа')], null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='fullName',
            field=models.TextField(blank=True, null=True, verbose_name='ФИО мужа/партнёра'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='placeOfRegistration',
            field=models.IntegerField(blank=True, choices=[(1, 'Санкт-Петербург'), (2, 'Ленинградская область'), (3, 'другой регион РФ'), (4, 'страна СНГ')], null=True, verbose_name='Место регистрации'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='professionalEducation',
            field=models.IntegerField(blank=True, choices=[(1, 'высшее'), (2, 'неоконченное высшее'), (3, 'среднее специальное'), (4, 'начальное профессиональное'), (5, 'отсутствует'), (6, 'обучается')], null=True, verbose_name='Профессиональное образование'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='registration',
            field=models.IntegerField(blank=True, choices=[(1, 'постоянная'), (2, 'временная')], null=True, verbose_name='Регистрация'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='telephoneNumber',
            field=models.TextField(blank=True, max_length=15, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='husbandinformation',
            name='workPlace',
            field=models.IntegerField(blank=True, choices=[(1, 'постоянное'), (2, 'временное'), (3, 'эпизодическое'), (4, 'не работает'), (5, 'состоит в центре занятости населения в качестве безработного')], null=True, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='socialeconomiccondition',
            name='income_level',
            field=models.IntegerField(blank=True, choices=[(1, 'высокий уровень'), (2, 'около двух прожиточных минимумов на человека'), (3, 'на уровне прожиточного минимума'), (4, 'ниже прожиточного минимума'), (5, 'нет дохода')], null=True, verbose_name='Уровень доходов клиента'),
        ),
        migrations.AlterField(
            model_name='sociallivingcondition',
            name='type_room',
            field=models.IntegerField(blank=True, choices=[(1, 'жилой дом'), (2, 'отдельная квартира'), (3, 'комната в коммунальной квартире'), (4, 'комната в общежитии'), (5, 'отсутствует')], null=True, verbose_name='Вид жилого помещения'),
        ),
        migrations.AlterField(
            model_name='socialpayment',
            name='basis_social_payments',
            field=models.IntegerField(blank=True, choices=[(1, 'нет оснований для оформления выплаты'), (2, 'имеется право на выплату'), (3, 'требует оформления'), (4, 'находится в стадии оформления'), (5, 'выплачивается')], null=True, verbose_name='Основания для социальных выплат'),
        ),
        migrations.AlterField(
            model_name='sourceincome',
            name='alimony',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Алименты/нотариальное соглашение о содержании ребенка'),
        ),
        migrations.AlterField(
            model_name='sourceincome',
            name='benefits',
            field=models.IntegerField(blank=True, choices=[(1, 'да'), (2, 'нет')], null=True, verbose_name='Льготы по коммунальным услугам'),
        ),
    ]
