# Generated by Django 3.0.8 on 2020-08-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0029_auto_20200813_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretationgage',
            name='risk_abuse',
            field=models.IntegerField(choices=[(0, 'проблемы не выявлены'), (3, 'выраженные признаки злоупотребления')], verbose_name='Риск злоупотребления'),
        ),
        migrations.AlterField(
            model_name='interpretationgage',
            name='risk_dependency',
            field=models.IntegerField(choices=[(0, 'проблемы не выявлены'), (2, 'имеются признаки зависимости')], verbose_name='Риск зависимости'),
        ),
    ]
