# Generated by Django 3.0.8 on 2020-08-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0030_auto_20200814_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretationboyko',
            name='aggressiveness',
            field=models.IntegerField(blank=True, choices=[(0, 'проблемы не выявлены'), (1, 'проблемы не выявлены'), (2, 'средняя агрессивность'), (3, 'сильная агрессивность'), (4, 'очень сильная агрессивность')], null=True, verbose_name='Агрессивность/аутоагрессивность'),
        ),
        migrations.AlterField(
            model_name='interpretationboyko',
            name='alarm',
            field=models.IntegerField(blank=True, choices=[(0, 'проблемы не выявлены'), (1, 'проблемы не выявлены'), (2, 'средняя тревога и депрессия'), (3, 'сильная тревога и депрессия'), (4, 'очень сильная тревога и депрессия')], null=True, verbose_name='Тревога и депрессия'),
        ),
        migrations.AlterField(
            model_name='interpretationboyko',
            name='child_parent',
            field=models.IntegerField(blank=True, choices=[(0, 'проблемы не выявлены'), (1, 'проблемы не выявлены'), (2, 'нестабильно проявляет заботу о детях'), (3, 'недостаточно заботится о детях'), (4, 'не заботится о детях')], null=True, verbose_name='Забота о детях/родителях'),
        ),
        migrations.AlterField(
            model_name='interpretationboyko',
            name='criticism',
            field=models.IntegerField(blank=True, choices=[(0, 'проблемы не выявлены'), (1, 'проблемы не выявлены'), (2, 'поверхностное понимание своего положения'), (3, 'сниженное понимание своего положения'), (4, 'стойкая утрата понимания своего положения')], null=True, verbose_name='Способность критически воспринимать свое состояние и поведение'),
        ),
        migrations.AlterField(
            model_name='interpretationboyko',
            name='family_relation',
            field=models.IntegerField(blank=True, choices=[(0, 'проблемы не выявлены'), (1, 'проблемы не выявлены'), (2, 'конфликтные отношения с родственниками'), (3, 'серьёзные конфликты с родственниками, приводящие к разрывам отношений'), (4, 'нет желания иметь/сохранять семью')], null=True, verbose_name='Семейные отношения'),
        ),
        migrations.AlterField(
            model_name='interpretationboyko',
            name='friends',
            field=models.IntegerField(blank=True, choices=[(0, 'проблемы не выявлены'), (1, 'проблемы не выявлены'), (2, 'сужение контактов с людьми'), (3, 'суженый круг общения, часты конфликты окружающими'), (4, 'отсутствие социальных связей')], null=True, verbose_name='Контакты с друзьями, знакомыми'),
        ),
        migrations.AlterField(
            model_name='interpretationboyko',
            name='leisure',
            field=models.IntegerField(blank=True, choices=[(0, 'проблемы не выявлены'), (1, 'проблемы не выявлены'), (2, 'бедная сфера интересов'), (3, 'бедная сфера интересов'), (4, 'отсутствие досуга, всё время посвящено употреблению')], null=True, verbose_name='Сфера досуга'),
        ),
        migrations.AlterField(
            model_name='interpretationboyko',
            name='memory_disorder',
            field=models.IntegerField(blank=True, choices=[(0, 'проблемы не выявлены'), (1, 'проблемы не выявлены'), (2, 'средне выраженные нарушения памяти, мышления, внимания'), (3, 'сильно выраженные нарушения памяти, мышления, внимания'), (4, 'очень сильно выраженные нарушения памяти, мышления, внимания')], null=True, verbose_name='Нарушения памяти, мышления, истощаемость'),
        ),
        migrations.AlterField(
            model_name='interpretationboyko',
            name='self_service',
            field=models.IntegerField(blank=True, choices=[(0, 'проблемы не выявлены'), (1, 'проблемы не выявлены'), (2, 'обслуживает себя минимально'), (3, 'трудности самообслуживания'), (4, 'не справляется с самообслуживанием')], null=True, verbose_name='Способности к самообслуживанию'),
        ),
        migrations.AlterField(
            model_name='interpretationboyko',
            name='work_activity',
            field=models.IntegerField(blank=True, choices=[(0, 'проблемы не выявлены'), (1, 'проблемы не выявлены'), (2, 'выраженные проблемы на работе, но не приводящие к её потере'), (3, 'серьёзные проблемы при работе, не позволяющие её сохранить'), (4, 'нет работы, не способен её самостоятельно найти и выполнять')], null=True, verbose_name='Трудовая (профессиональная) деятельность'),
        ),
    ]
