# Generated by Django 3.0.8 on 2020-08-16 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0031_auto_20200814_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretationboyko',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 15, 31, 30, 173027), verbose_name='Текущая дата и время'),
        ),
    ]
