# Generated by Django 3.0.8 on 2020-08-16 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0032_interpretationboyko_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretationboyko',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 12, 34, 1, 290137, tzinfo=utc), verbose_name='Текущая дата и время'),
        ),
    ]
