# Generated by Django 3.0.8 on 2020-08-16 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0033_auto_20200816_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretationboyko',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Текущая дата и время'),
        ),
    ]
