# Generated by Django 3.0.8 on 2020-08-16 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0034_auto_20200816_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretationgage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Текущая дата и время'),
        ),
        migrations.AddField(
            model_name='interpretationsocrates',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Текущая дата и время'),
        ),
    ]
