# Generated by Django 3.0.8 on 2020-08-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0036_auto_20200816_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretationboyko',
            name='date',
            field=models.DateTimeField(default='2020-08-16 13:18:21', verbose_name='Дата и время прохождения теста'),
        ),
        migrations.AlterField(
            model_name='interpretationgage',
            name='date',
            field=models.DateTimeField(default='2020-08-16 13:18:21', verbose_name='Дата и время прохождения теста'),
        ),
        migrations.AlterField(
            model_name='interpretationsocrates',
            name='date',
            field=models.DateTimeField(default='2020-08-16 13:18:21', verbose_name='Дата и время прохождения теста'),
        ),
    ]
