# Generated by Django 3.0.8 on 2020-08-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0037_auto_20200816_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretationboyko',
            name='date',
            field=models.DateTimeField(default='20202020-АвгАвг-1616UTC0101:0808:5050', verbose_name='Дата и время прохождения теста'),
        ),
        migrations.AlterField(
            model_name='interpretationgage',
            name='date',
            field=models.DateTimeField(default='2020-08-16 13:20:50', verbose_name='Дата и время прохождения теста'),
        ),
        migrations.AlterField(
            model_name='interpretationsocrates',
            name='date',
            field=models.DateTimeField(default='2020-08-16 13:20:50', verbose_name='Дата и время прохождения теста'),
        ),
    ]
