# Generated by Django 3.0.8 on 2020-08-16 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0038_auto_20200816_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretationboyko',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время прохождения теста'),
        ),
        migrations.AlterField(
            model_name='interpretationgage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время прохождения теста'),
        ),
        migrations.AlterField(
            model_name='interpretationsocrates',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время прохождения теста'),
        ),
    ]
