# Generated by Django 3.0.8 on 2020-08-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0039_auto_20200816_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Должность'),
        ),
    ]
