# Generated by Django 3.0.8 on 2020-08-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_center_app', '0042_auto_20200819_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testboyko',
            name='attempt',
            field=models.IntegerField(choices=[(1, 'Первичная'), (2, 'Вторичная')], verbose_name='Диагностика'),
        ),
        migrations.AlterField(
            model_name='testgage',
            name='attempt',
            field=models.IntegerField(choices=[(1, 'Первичная'), (2, 'Вторичная')], verbose_name='Диагностика'),
        ),
        migrations.AlterField(
            model_name='testsocrates',
            name='attempt',
            field=models.IntegerField(choices=[(1, 'Первичная'), (2, 'Вторичная')], verbose_name='Диагностика'),
        ),
    ]
